export enum TaskQuadrant {
    URGENT_IMPORTANT="URGENT_IMPORTANT",
    NO_URGENT_IMPORTANT="NO_URGENT_IMPORTANT",
    URGENT_NO_IMPORTANT="URGENT_NO_IMPORTANT",
    NO_URGENT_NO_IMPORTANT="NO_URGENT_NO_IMPORTANT",
    NOT_CLASSIFIED="NOT_CLASSIFIED"
}
